platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: git-repo
outputs:
  - name: mvn-package-output

run:
  path: "mvn"
  args: ["-f", "git-repo/pom.xml", "clean"]
  args: ["-f", "git-repo/pom.xml", "package"]
  args: ["-f", "git-repo/pom.xml", "sonar:sonar -Dsonar.host.url=http://54.209.104.148:9001/ -Dsonar.sources=src/main/java"]
