resources:
- name: branch-dev
  type: git
  source:
    uri: https://github.com/DeenaDhayalanB/springpetclinic.git
    branch: master

- name: PCF-Dev
  type: cf
  source:
    api: {{pcf-api}}
    username: {{pcf-username}}
    password: {{pcf-password}}
    organization: {{pcf-organization}}
    space: {{pcf-space}}
    skip_cert_check: false

jobs:
- name: udm
  serial: true
  plan:
  - get: branch-dev
    trigger: true
  - task: mvn-package
      privileged: true
      file: branch-dev/package.yml
  - put: PCF-Dev
    params:
      manifest: branch-dev/manifest.yml
      path: mvn-package-output/target/udm-0.1.war
