resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/DeenaDhayalanB/petclinic.git
      branch: master

jobs:
  - name: maven-package
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
    - task: maven-package
      privileged: true
      file: git-repo/package.yml
